#!/bin/sh

device="$1"
dir="$2"
width="$3"
height="$4"
left="$5"
top="$6"
suf="$7"

if [ "$dir" = "" -o "$top" = "" ]; then
    echo "Usage: scan DEVICE DIR WIDTH HEIGHT LEFT TOP [suffix]"
    exit
fi

cd "$dir"
norm="pnmnorm -bvalue 30 -wvalue 235"

echo "scanimage -d $device --mode=color --resolution 600dpi -x $width -y $height -l $left -t $top" >> /tmp/sc

scanimage -d $device --mode=color --resolution 400dpi\
    -x $width -y $height -l $left -t $top |\
     pnmflip -topbottom -leftright | pnmtotiff > sleeve.ppm

tifftopnm < sleeve.ppm | $norm | cjpeg > sleeve$suf.jpg

tifftopnm < sleeve.ppm | $norm | pnmscale -xsize 700 | cjpeg \
    -quality 90 > "$dir/display$suf.jpg"

tifftopnm < sleeve.ppm | $norm | pnmscale -xsize 200 | pnmtopng \
    > thumbnail$suf.png

tifftopnm < sleeve.ppm | $norm | pnmscale -xsize 100 | pnmtopng \
    > micro$suf.png

tifftopnm < sleeve.ppm | $norm | pnmtopng > "sleeve$suf.png"

rm -f sleeve.tiff sleeve.ppm
